# Generated by Django 3.1.7 on 2021-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0002_auto_20210402_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='link',
        ),
        migrations.AddField(
            model_name='blogdata',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
