# Generated by Django 3.1.7 on 2021-04-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='link',
        ),
        migrations.AddField(
            model_name='blogdata',
            name='content',
            field=models.JSONField(default='{}'),
        ),
    ]
